### ISSUE TITLE
Install Kubewarden with PSA restricted

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-end-to-end-tests#146]
Starting from 1.23.0-beta2, KW stack can be deployed inside a Namespace with the Pod Security Standards set to `restricted`.

### Acceptance criteria

If KW >= 1.23, create `kubewarden` namespace with PSA `restricted`:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: kubewarden
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.25 <k8s version of cluster>
EOF
```
